export type LyricsSection = {
  label: string
  lines: string[]
  pullQuote?: string
  muted?: boolean
}

export type TrackLyrics = {
  id: string
  trackNum: string
  title: string
  stampId: string
  manifest: string[]
  bpm: number
  key: string
  duration: string
  spotifyId: string
  sections: LyricsSection[]
}

export const SPOTIFY_ALBUM_ID = '5poA9SAx0Xiz1cf17fWBLS'

export const TRACKS_LYRICS: TrackLyrics[] = [
  {
    id: '01',
    trackNum: '01',
    title: 'KING',
    stampId: 'STAMP_ID: 01_KING_V12',
    manifest: ['[Intro: Duke Edwards]', '[Verse 1: Ye & Duke Edwards]', '[Verse 2: Ye & Duke Edwards]', '[Outro: Ye]'],
    bpm: 88,
    key: 'C MINOR',
    duration: '02:06',
    spotifyId: '4LP6bmyAxdMNrqUrMpaVQ8',
    sections: [
      {
        label: 'SECTION_00: INTRO — DUKE EDWARDS',
        lines: [
          'The time is now, right now',
          'This is the hour, this is the new dawn, this is the new day',
          'Now is the time, for nature and all her glory have named you her king',
          'She has named you the king',
          'King, king, king',
          'Named you the king',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE & DUKE EDWARDS',
        lines: [
          'This that feeling we need more of',
          'The hatin\' just brought me more love',
          'Guarantee my vices different than yours was',
          'Drunk off power and I was pourin\' up',
          'When all y\'all treated me like an orphan',
          'The classes turned me to Daddy Warbucks',
          'The stables for the \'Raris and Porsches',
          'The fame was only gettin\' me more buzzed',
          'Some of my love ones turned lost ones',
          'The pain was truly blurrin\' my thoughts up',
          'I brought a white queen to the altar',
          'Couldn\'t happen without Martin Luther, the',
        ],
        pullQuote: 'NAMED YOU THE KING',
      },
      {
        label: 'SECTION_02: VERSE — YE & DUKE EDWARDS',
        lines: [
          'What\'s the Kelly Price? What\'s the Kevin Costner?',
          'What\'s the Kelly cost? Birkin, it\'s a tossup',
          'Is it really love when it\'s bought love?',
          'She would never let me fuck if I was fucked up',
          'Why you think we run it up for?',
          'The truth hurts homie, tough love',
          'The hero became the villain now',
          'We gon\' send it up and go a million miles',
          'And she ain\'t dealin\' with no Shallow Hals',
          'She want that Iron Man like Gwyneth Paltrow',
          'It\'s why people throwin\' in the towel for',
          'That dopeness I distribute like Alpo',
          'They don\'t take it to the heights that I\'ll go',
          'They burnt out on that Black & Mild flow',
          'They had to run, but Yeezy got it now though',
          'It\'s over with for them, like it\'s an outro',
        ],
      },
      {
        label: 'SECTION_03: OUTRO — YE',
        lines: ['You know what season it is'],
        muted: true,
      },
    ],
  },
  {
    id: '03',
    trackNum: '03',
    title: 'FATHER',
    stampId: 'STAMP_ID: 03_FATHER_V15',
    manifest: ['[Intro: Johnnie Frierson]', '[Verse 1: Ye]', '[Bridge]', '[Verse 2: Travis Scott]', '[Outro: Johnnie Frierson & Travis Scott]'],
    bpm: 76,
    key: 'D MINOR',
    duration: '02:49',
    spotifyId: '5pfn68duSmBKo4FhYknOms',
    sections: [
      {
        label: 'SECTION_00: INTRO — JOHNNIE FRIERSON',
        lines: [
          'Give us love another day',
          'And hear our prayers',
          'Please, Lord, when, whenever we pray',
          'Father, You\'ve been, You\'ve been good',
          'I just wanna say thank you, Lord',
          'I just wanna say thank you, Lord',
          'You\'ve been better to us',
          'Than we\'ve been to ourselves',
          'Father',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Know you wonder where the F he been',
          'But I\'m back to life like an Epi-Pen',
          'And she still in the leopard skin',
          'And I check me out, then check me in',
          'See this coat, nigga?',
          'Bye-bye to my old self',
          'Wake up to the new me',
          'I used to be on Worldstar',
          'Now I\'m making Newsweek',
          'I used to hang on the 9',
          'Now I bought two streets',
          'Cottage Grove to King Drive',
          'Yeah, this life is a movie',
        ],
        pullQuote: 'BYE-BYE TO MY OLD SELF WAKE UP TO THE NEW ME',
      },
      {
        label: 'SECTION_02: VERSE — TRAVIS SCOTT',
        lines: [
          'Know you wonderin\' where the F I been',
          'I been goin\' hard like a crack syringe',
          'I been breakin\' bad, now I\'m back again',
          'Gettin\' mil\' tickets, no rafflin\'',
          'You see these kicks, nigga?',
          'Made checks off the right steps',
          'More vision than some Oakleys',
          'She used to be a lone star',
          'Wakin\' up to lucies',
          'Used to live up in the 7',
          'Now I bought two streets',
          'Always team Luther King Drive',
          'Now it\'s Malibu Beach',
        ],
      },
      {
        label: 'SECTION_03: OUTRO — JOHNNIE FRIERSON & TRAVIS SCOTT',
        lines: ['Father', 'Help us now', 'Father'],
        muted: true,
      },
    ],
  },
  {
    id: '05',
    trackNum: '05',
    title: 'PUNCH DRUNK',
    stampId: 'STAMP_ID: 05_PUNCHDRUNK_V06',
    manifest: ['[Intro]', '[Verse: Ye]', '[Chorus]'],
    bpm: 82,
    key: 'E FLAT MAJOR',
    duration: '01:48',
    spotifyId: '4bWZz15GR1EE8E8x23rDWV',
    sections: [
      {
        label: 'SECTION_00: INTRO / HOOK',
        lines: [
          'This time, we takin\' over',
          'Outer space, goin\' solar',
          'Back then, they showed no love',
          'Punch drunk, hungover, huh',
          'Punch drunk, hungover on love',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'I had to learn to read between the lines',
          'Overboard when they mention me in Times',
          'Know the Lord\'s intervention was divine',
          'Political and social tensions on the climb',
          'Not to mention, they forget to mention',
          'How I\'m swingin\' through like Sonny Liston in his prime',
          'Used to dream about this every day',
          'The way that He\'d deliver me',
          'I know some churchgoin\' women prayed',
          'What\'s worse is livin\' in conditions made',
          'Hearses takin\' good men away',
          'Fathers in the penitentiary',
          'Mothers fightin\' for a livin\' wage',
        ],
        pullQuote: 'PUNCH DRUNK HUNGOVER ON LOVE',
      },
      {
        label: 'SECTION_02: CHORUS',
        lines: [
          'But this time, we takin\' over',
          'Outer space, goin\' solar',
          'Punch drunk, hungover',
          'Punch drunk, hungover',
          'Over on love',
          'Oh, yes, I can, oh, yes, I can, oh, yes, I can',
          'I can do all things through Christ',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '06',
    trackNum: '06',
    title: 'WHATEVER WORKS',
    stampId: 'STAMP_ID: 06_WHATEVERWORKS_V09',
    manifest: ['[Intro]', '[Verse: Ye]', '[Outro]'],
    bpm: 90,
    key: 'B FLAT MINOR',
    duration: '01:59',
    spotifyId: '7GVuAK4EmYP7gvlXA4JXqU',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'I\'ll always forgive you',
          'I\'ll always forgive you',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Had a change of heart, I felt different at first',
          'Lot of pain, lot of hurt, but still, could\'ve been worse',
          'In a big city, in pole position, when you reverse',
          'She had that new convertible, the Lil Uzi Vert',
          'Down payment on the cars that you love went on her purse',
          'Go to work or whatever she said, whatever works',
          'Unemployed, early in the story, I was startin\' off',
          'Had the Ford Focus before I couldn\'t afford a car',
          'Now she finna throw it like she do it for an Audemar',
          'Meetin\' with some ministers and kings, I was noddin\' off',
          'Haven\'t seen a king that was royal as my daughters are',
          'All fallin\' for the fake news, man, I\'m loggin\' off',
          'They sent shots while we spin blocks in an armored car',
        ],
        pullQuote: 'WHATEVER WORKS WORKS',
      },
      {
        label: 'SECTION_02: VERSE (CONT.)',
        lines: [
          'Now they want the tea \'cause it\'s pipin\' hot',
          'Life gave me lemons, made an Arnold Palmer on the rocks',
          'I feel like Arnold Schwarzenegger',
          'Contract terminator on the spot',
          'They wanna back and forth, I\'d rather not',
          'Yeezy airbags when I\'m crashin\' out',
          'They gon\' hate it with a passion now, I love it',
        ],
      },
    ],
  },
  {
    id: '08',
    trackNum: '08',
    title: 'SISTERS AND BROTHERS',
    stampId: 'STAMP_ID: 08_SISTERS_V08',
    manifest: ['[Intro: Jonah Thompson]', '[Verse: Ye & Jonah Thompson]', '[Bridge: Loleatta Holloway]', '[Outro: Jonah Thompson]'],
    bpm: 100,
    key: 'A FLAT MAJOR',
    duration: '02:46',
    spotifyId: '1FpjiEapAG8XJdVSI0tvdc',
    sections: [
      {
        label: 'SECTION_00: INTRO — JONAH THOMPSON',
        lines: [
          'Sisters and brothers',
          'And all of my friends',
          'And all of my friends',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE & JONAH THOMPSON',
        lines: [
          'It\'s finna get a lot more dangerous',
          'My brothers move a lot like strangers',
          'They say I\'m blackin\' out like Akon',
          'I\'m feelin\' more Khan like Genghis',
          'What they gon\' do? What they gon\' do with \'em?',
          'Take some time off, they act like they don\'t remember',
          'Couple fortnights and at least two winters',
          'Back with the head taps and the head spinners',
          'I been blowin\' money fast, it could not go quicker',
          'Throw it in the bag like the fastball pitcher',
          'Designated hatin\' for the designated hitter',
        ],
        pullQuote: 'SISTERS AND BROTHERS AND ALL OF MY FRIENDS',
      },
      {
        label: 'SECTION_02: VERSE (CONT.)',
        lines: [
          'Give it all you got, it does not make a difference',
          'I\'ve been high off livin\', man, I\'m finna OD',
          'Wifey just hit the runway OT',
          'They think we off key, but it\'s anarchy',
          'Benz on the 45, goin\' mach three',
          'It\'s nothin\' to discuss, so we not gon\' speak',
          'They never gave justice, so y\'all don\'t know peace',
          'Bank account filled with the root of all evil',
          'Antihero, vigilante',
        ],
      },
      {
        label: 'SECTION_03: BRIDGE — LOLEATTA HOLLOWAY',
        lines: [
          'A lady looked at me and she said',
          '"Never let someone know that they\'re getting you down"',
          '"You see, if you let them know that they\'re getting you down, honey"',
          '"They gon\' kick you really far"',
          'But you know what I told her?',
        ],
        muted: true,
      },
      {
        label: 'SECTION_04: OUTRO — JONAH THOMPSON',
        lines: [
          'The sign of Jesus, it\'s all in my room',
          'I believe He\'s coming, He\'ll be here soon',
          'I\'m gonna praise Him',
          'I got involved with the Father',
          'I got involved with the Son',
          'I\'m gonna stay involved with the',
          'With the Holy Spirit',
          'It\'s all in one',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '09',
    trackNum: '09',
    title: 'BULLY',
    stampId: 'STAMP_ID: 09_BULLY_V20',
    manifest: ['[Intro: Sample]', '[Verse: Ye]', '[Outro: Sample]'],
    bpm: 95,
    key: 'G MINOR',
    duration: '02:27',
    spotifyId: '6KhDb86ThnlKirRw1UBZGb',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'Ha, ha',
          'Serotonin, serotonin',
          'Gets me goin\' \'til the mornin\'',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Is this what you wanted?',
          'Serotonin',
          'Do you want it? Do you want it?',
          'Getting dark outside, dopamine declined',
          'Never satisfied, \'less you by my side',
          'Fifteen thousand lunch, twenty bottles drunk',
          'Left without you, love, I\'m completely numb',
          'System overdrive, algorithm\'s fried',
          'You consume my mind, you got all my time',
          'Face is paralyzed, fully compromised',
          'Make a grown man cry, girl, let\'s make a child',
        ],
        pullQuote: 'SYSTEM OVERDRIVE ALGORITHM\'S FRIED',
      },
      {
        label: 'SECTION_02: OUTRO',
        lines: [
          'Serotonin, serotonin',
          'Gets me goin\' \'til the mornin\'',
          'Is this what you wanted?',
          'Serotonin',
          'Do you want it? Do you want it?',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '11',
    trackNum: '11',
    title: "I CAN'T WAIT",
    stampId: 'STAMP_ID: 11_CANTWAIT_V04',
    manifest: ['[Intro: Sample]', '[Verse: Ye]', '[Chorus: Sample]'],
    bpm: 86,
    key: 'F MAJOR',
    duration: '02:07',
    spotifyId: '163l4Itf8oDEK7ZYdVm22N',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'I can\'t bare to live my life alone',
          'I\'ve grown impatient for love',
          'Too patient for love',
          'To call',
          'I can\'t bare',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'She eatin\' up the time, she was designed for it',
          'I\'d die to rearrange and move my mind forward',
          'Oh, move my mind forward',
          'This thing is gettin\' crazy, goin\' blind for it',
          'They hate to see the system actually figured out',
          'They want you caught up in distraction, fear, and doubt',
          'I\'d rather focus on the love that\'s been around',
          'Take all the stress to UPS and ship it out',
          'No executive could ever run they mouth',
          'I been consecutive at shuttin\' shit down',
          'High-speed drives through the scenic route',
          'High fashion when people see us out',
        ],
        pullQuote: 'CAN\'T HURRY LOVE',
      },
      {
        label: 'SECTION_02: CHORUS',
        lines: [
          'Can\'t hurry love',
          'No, you just have to wait',
          'She said, "Love don\'t come easy"',
          'It\'s a game of give and take',
          'How many heartaches must I stand',
          'Before I find a love?',
          'I remember mama said',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '12',
    trackNum: '12',
    title: 'WHITE LINES',
    stampId: 'STAMP_ID: 12_WHITELINES_V07',
    manifest: ['[Intro]', '[Verse: Ye]', '[Chorus: Sample / Andre Troutman]'],
    bpm: 72,
    key: 'D FLAT MAJOR',
    duration: '02:10',
    spotifyId: '3bbjDFVu9BtFtGD2fZpVfz',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'Why do birds suddenly appear',
          'Every time that you are near?',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Sometimes I belong by myself, yeah',
          'Don\'t feel at home by myself, yeah',
          'It ain\'t the same feeling with somebody else',
          'Feel like a clone of myself, yeah',
          'See, I ain\'t gotta lie, rather tell the truth',
          'But I tell the truth \'bout everything',
          'Everything, everything',
          'Yeah, I tell the truth \'bout everything',
          'Sometimes, I just don\'t wanna feel',
          'Attitudes, that appears',
          'Why I\'m still, yeah, I\'m still',
          'Close to you, close to you',
          'All that we\'ve been through',
          'We kept us here together',
        ],
        pullQuote: 'CLOSE TO YOU CLOSE TO YOU',
      },
      {
        label: 'SECTION_02: CHORUS',
        lines: [
          'Birds suddenly appear',
          'Every time that you\'re near',
          'Just like me, they long to be',
          'Close to you',
          'On the day that you were born',
          'The angels got together',
          'And decided to create a dream come true',
          'So they sprinkled moondust in your hair',
          'And golden starlight in your eyes',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '13',
    trackNum: '13',
    title: 'CIRCLES',
    stampId: 'STAMP_ID: 13_CIRCLES_V03',
    manifest: ['[Intro]', '[Verse: Ye & Don Toliver]'],
    bpm: 110,
    key: 'A MINOR',
    duration: '01:31',
    spotifyId: '1udGa2Ww3YIVSp5X4OMHFQ',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'Oh, Lord, I can\'t miss this',
          'Oh, Lord, I got issues',
          'Oh, Lord, I don\'t need shit',
          'Oh, Lord, hitting this one',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE & DON TOLIVER',
        lines: [
          'Circles, circles, circles, circles',
          'Circles, circles, circles, circles',
          'She doing it right to keep me up',
          'Staying the night, but it\'s never enough',
          'What we gain going in circles?',
          'Circles, circles, circles, circles',
          'Circles, circles, circles, circles',
        ],
        pullQuote: 'WHAT WE GAIN GOING IN CIRCLES?',
      },
    ],
  },
  {
    id: '14',
    trackNum: '14',
    title: 'PREACHER MAN',
    stampId: 'STAMP_ID: 14_PREACHERMAN_V11',
    manifest: ['[Intro: Sample]', '[Verse 1: Ye]', '[Verse 2: Ye]', '[Outro: Sample]'],
    bpm: 78,
    key: 'E MINOR',
    duration: '03:01',
    spotifyId: '0fD7KBtQgPR1YCtuPAsyZJ',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'This ring that I hold, I',
          'This ring that I hold, I give to you',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Break in, they ain\'t let us in',
          'We passed on the settlement',
          'This path, I don\'t recommend',
          'We passed what they expected, man',
          'I go where they never can',
          'I float, I don\'t ever land',
          'When it\'s dark, you don\'t know where you goin\'',
          'Need a light-bearer to lead you home',
          'Light \'em up, beam me up',
          'The only GOAT, the genius one',
          'They switchin\' sides, I seen it comin\'',
          'The plot twist, a convenient one',
        ],
        pullQuote: 'I GO WHERE THEY NEVER CAN I FLOAT I DON\'T EVER LAND',
      },
      {
        label: 'SECTION_02: VERSE — YE (CONT.)',
        lines: [
          'Look, nobody finna extort me',
          'Even when they record me, I\'ma keep it more G',
          'Hand me a drink \'fore I get more deep',
          'She hate sports \'less she watchin\' from the floor seats',
          'I hate that God didn\'t make a couple more of me',
          'And all my haters in the courts act accordingly',
          'They imitate the sound, call it forgery',
          'What we doing\'s more important, more importantly',
          'Basically, went out my way to make a way for you',
          'Basically, we finna take \'em higher places through it',
          'Way improved, and like a beta, we gon\' stay improvin\'',
          'This the light that\'s gon\' illuminate the way we movin\'',
          'Trust in me, we goin\' God mode, the theory\'s proven',
        ],
      },
      {
        label: 'SECTION_03: OUTRO',
        lines: [
          'I walk up to the preacher man',
          'Just to take your lovely hand',
          'And give to you',
          'I give to you',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '15',
    trackNum: '15',
    title: 'BEAUTY AND THE BEAST',
    stampId: 'STAMP_ID: 15_BATB_V14',
    manifest: ['[Intro]', '[Verse: Ye]', '[Outro]'],
    bpm: 68,
    key: 'F SHARP MINOR',
    duration: '01:45',
    spotifyId: '6pxHjkpwGmg97Yn5HcwNTn',
    sections: [
      {
        label: 'SECTION_00: INTRO / VERSE — YE',
        lines: [
          'It\'s been a long time coming',
          'Fresh new tires, I\'m still running',
          'It\'s a few things I\'m overcoming',
          'When the check\'s still clear, still',
          'Think about it every night and day',
          'To try to stay away, to keep my heart in here tucked',
          'Don\'t take this as disrespect, I\'m sitting here trying to redirect them',
        ],
        pullQuote: 'NEVER PUT ME DOWN',
      },
      {
        label: 'SECTION_01: VERSE — YE (CONT.)',
        lines: [
          'Think about it every night and day',
          'To try to stay away, to keep my heart in here tucked',
          'Don\'t take this as disrespect, I\'m still here in a trifecta',
          'It\'s been a long time coming',
          'Fresh new tires, I\'m still running',
          'It\'s a few things I\'m overcoming',
        ],
      },
      {
        label: 'SECTION_02: OUTRO',
        lines: [
          'Never put me down',
          'Put me down, put me down, down, down',
          'Never put me down',
          'Put me down, put me down, down, down',
        ],
        muted: true,
      },
    ],
  },
  {
    id: '16',
    trackNum: '16',
    title: 'DAMN',
    stampId: 'STAMP_ID: 16_DAMN_V10',
    manifest: ['[Intro]', '[Verse: Ye]'],
    bpm: 74,
    key: 'A FLAT MINOR',
    duration: '02:02',
    spotifyId: '4dm2VMjIs1JlGZp2TePJaE',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'I wish feeling never comes',
          'I wish feeling never comes',
          'I wish feeling never comes',
          'I wish feeling never comes',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'Damn, damn, damn',
          'Did I ruin your plans, plans, plans?',
          'Well that\'s the way I am',
          'Gave it all I had',
          'My feelings are the facts of it',
          'It\'s more of me to navigate',
          'Pray we never crash, crash, crash',
          'Today will always last',
          'We\'re the ones that pass away',
          'So, baby, did you laugh today?',
          'This one\'s for the path we take',
          'Magic hourglass',
          'At least I gave you that',
        ],
        pullQuote: 'DID I RUIN YOUR PLANS?',
      },
    ],
  },
  {
    id: '18',
    trackNum: '18',
    title: 'THIS ONE HERE',
    stampId: 'STAMP_ID: 18_THISONEHERE_V05',
    manifest: ['[Intro]', '[Verse 1: Ye]', '[Chorus]', '[Verse 2: Ye]', '[Outro]'],
    bpm: 108,
    key: 'G MAJOR',
    duration: '03:01',
    spotifyId: '7uGrdyEErKPSA3oiJQHxQ6',
    sections: [
      {
        label: 'SECTION_00: INTRO',
        lines: [
          'To waste, no time',
          'Kick out that ego right out of the door',
          'Right now, showtime',
          'Come on, it\'s go time',
          'Come on, it\'s go time',
        ],
      },
      {
        label: 'SECTION_01: VERSE — YE',
        lines: [
          'I\'m going to war, babe',
          'I\'m going to war',
          'Don\'t waste, no time',
          'Right now, it\'s showtime',
          'Come on, it\'s go time',
          'Kick out that ego right out of the door',
          'Come on, it\'s go time',
          'I\'m going to war, babe',
          'I\'m going to war',
          'Yes, I need this here, I\'ve been fighting for',
          'I\'ve been fighting for my life',
        ],
        pullQuote: 'THIS ONE HERE THIS FIRE FIRE',
      },
      {
        label: 'SECTION_02: VERSE — YE (CONT.)',
        lines: [
          'This that new phone',
          'This that healed and moved on',
          'This that life that you want',
          'You can\'t wait for it too long',
          'No, I don\'t wanna hold out too long',
          'When I\'m in that mode, can\'t do wrong',
          'And you know we on go, we too gone',
          'Taking off, five, four, three, two, one',
        ],
      },
      {
        label: 'SECTION_03: VERSE — YE (CONT.)',
        lines: [
          'This that new us',
          'Started from the ground and moved up',
          'You ain\'t got love for yourself',
          'You ain\'t never felt a true love',
          'I can see where your heart is',
          'Broken pieces before us',
          'When the evening is darkest',
          'I know dawn is upon us',
          'Come on!',
          'We came ready, ready, for the rising sun',
        ],
      },
    ],
  },
]
